## Chapter 1:Getting & Knowing your Data

In [1]:
import pandas as pd

In [2]:
import pandas as pd

Employee_Dataset = pd.read_csv("Employee Dataset - TSV (1).txt", sep="\t")

Employee_Dataset.head()

,Employee Name,Age,Last Working Day,Department,Education,Gender,Marital Status,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
0,Jitesh,41,31-12-9999,Training,Masters,Male,Single,5993,8,11,3
1,Sanjit,49,31-12-9999,Sales,Masters,Male,Married,5130,1,23,4
2,John,37,31-12-9999,R&D,Doctorate,Male,Single,2090,6,15,3
3,Sandra,33,31-12-9999,Software Development,Undergraduate,Female,Married,2909,1,11,3
4,Madhu,27,31-12-9999,R&D,Masters,Male,Married,3468,9,12,3

In [3]:
import os
print(os.listdir())

['.ipynb_checkpoints', '01_Python_programming', '02_Python_Libraries_Introduction', 'Employee Dataset - TSV (1).txt', 'employee_data.csv', 'Euro_2012_stats_TEAM.csv', 'new_employee_data.xlsx', 'Pandas_Crash_Course.ipynb', 'Python Data Structures.ipynb', 'Server.xlsx']

In [4]:
Employee_Dataset = pd.read_table("Employee Dataset - TSV (1).txt", sep="\t")

Employee_Dataset.head()

,Employee Name,Age,Last Working Day,Department,Education,Gender,Marital Status,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
0,Jitesh,41,31-12-9999,Training,Masters,Male,Single,5993,8,11,3
1,Sanjit,49,31-12-9999,Sales,Masters,Male,Married,5130,1,23,4
2,John,37,31-12-9999,R&D,Doctorate,Male,Single,2090,6,15,3
3,Sandra,33,31-12-9999,Software Development,Undergraduate,Female,Married,2909,1,11,3
4,Madhu,27,31-12-9999,R&D,Masters,Male,Married,3468,9,12,3

## 1.1 Perform Initial Analysis

In [5]:
#Function - ()
#Attribute

In [6]:
Employee_Dataset.shape

(25, 11)

#### Terminology Alert

- Rows - Observations/Record
- Column - Features/Parameters

In [7]:
Employee_Dataset.isnull().sum() #Chain of functions,Chain of commands

Employee Name          0
Age                    0
Last Working Day       0
Department             0
Education              0
Gender                 1
Marital Status         2
Monthly Income         0
Years of Experience    0
Percent Salary Hike    0
Performance Rating     0
dtype: int64

In [8]:
Employee_Dataset.dtypes

Employee Name          object
Age                     int64
Last Working Day       object
Department             object
Education              object
Gender                 object
Marital Status         object
Monthly Income          int64
Years of Experience     int64
Percent Salary Hike     int64
Performance Rating      int64
dtype: object

In [9]:
Employee_Dataset.describe(include ="all")

,Employee Name,Age,Last Working Day,Department,Education,Gender,Marital Status,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
count,25,25.00000,25,25,25,24,23,25.000000,25.000000,25.000000,25.000000
unique,23,NaN,3,5,3,2,3,NaN,NaN,NaN,NaN
top,Adam,NaN,31-12-9999,Software Development,Masters,Male,Single,NaN,NaN,NaN,NaN
freq,3,NaN,23,13,13,16,9,NaN,NaN,NaN,NaN
mean,NaN,35.08000,NaN,NaN,NaN,NaN,NaN,4674.040000,2.320000,14.760000,3.200000
std,NaN,8.40595,NaN,NaN,NaN,NaN,NaN,3427.734474,2.939955,4.075128,0.408248
min,NaN,22.00000,NaN,NaN,NaN,NaN,NaN,2028.000000,0.000000,11.000000,3.000000
25%,NaN,30.00000,NaN,NaN,NaN,NaN,NaN,2670.000000,0.000000,12.000000,3.000000
50%,NaN,34.00000,NaN,NaN,NaN,NaN,NaN,3298.000000,1.000000,13.000000,3.000000
75%,NaN,37.00000,NaN,NaN,NaN,NaN,NaN,5130.000000,5.000000,17.000000,3.000000
max,NaN,59.00000,NaN,NaN,NaN,NaN,NaN,15427.000000,9.000000,23.000000,4.000000

## 1.2 Find Out The Monthly Income Of Employees

In [10]:
Employee_Dataset.nunique()

Employee Name          23
Age                    18
Last Working Day        3
Department              5
Education               3
Gender                  2
Marital Status          3
Monthly Income         23
Years of Experience     9
Percent Salary Hike    12
Performance Rating      2
dtype: int64

In [11]:
print(Employee_Dataset["Monthly Income"].unique())

[ 5993  5130  2090  2909  3468  3068  2670  2693  9526  5237  2426  4193
  2911  2661  2028  9980  3298  2935 15427  3944  4011  3407 11994]

## 1.3 Give Me The List Of Top 5 Monthly Income

In [12]:
Employee_Dataset.sort_values(by="Monthly Income", ascending=False)[["Department","Monthly Income"]].head(10) #chain Methods

              Department  Monthly Income
20                 Sales           15427
24                   R&D           11994
17  Software Development            9980
8                    R&D            9526
0               Training            5993
9   Software Development            5237
1                  Sales            5130
13  Software Development            4193
22           Development            4011
21                   R&D            3944

## 1.3 Give Me The List Of Least 5 Monthly Income

In [13]:
Employee_Dataset.sort_values(by="Monthly Income", ascending=True)[["Department","Monthly Income"]].head(10) #chain Methods

              Department  Monthly Income
16  Software Development            2028
2                    R&D            2090
10  Software Development            2426
12  Software Development            2426
11  Software Development            2426
15  Software Development            2661
6   Software Development            2670
7                    R&D            2693
3   Software Development            2909
14  Software Development            2911

## Chapter 2 - Data Cleaning

In [14]:
Employee_Dataset

,Employee Name,Age,Last Working Day,Department,Education,Gender,Marital Status,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
0,Jitesh,41,31-12-9999,Training,Masters,Male,Single,5993,8,11,3
1,Sanjit,49,31-12-9999,Sales,Masters,Male,Married,5130,1,23,4
2,John,37,31-12-9999,R&D,Doctorate,Male,Single,2090,6,15,3
3,Sandra,33,31-12-9999,Software Development,Undergraduate,Female,Married,2909,1,11,3
4,Madhu,27,31-12-9999,R&D,Masters,Male,Married,3468,9,12,3
5,Robert,32,31-12-9999,R&D,Masters,Male,Single,3068,0,13,3
6,Megan,59,31-12-9999,Software Development,Masters,Female,Married,2670,4,20,4
7,Matt,30,31-12-9999,R&D,Doctorate,Male,Divorced,2693,1,22,4
8,Will,38,01-03-2012,R&D,Doctorate,Male,Single,9526,0,21,4
9,George,36,31-12-9999,Software Development,Masters,NaN,Married,5237,6,13,3
10,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
11,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
12,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
13,Emma,29,31-12-9999,Software Development,Undergraduate,Female,Single,4193,0,12,3
14,Vin,31,31-12-9999,Software Development,Undergraduate,Male,NaN,2911,1,17,3
15,Richard,34,31-12-9999,Software Development,Undergraduate,Male,Divorced,2661,0,11,3
16,Clint,28,31-12-9999,Software Development,Undergraduate,Male,Single,2028,5,14,3
17,Kate,29,31-12-9999,Software Development,Undergraduate,Female,NaN,9980,1,11,3
18,Morgan,32,31-12-9999,Software Development,Undergraduate,Male,Divorced,3298,0,12,3
19,Mel,22,01-06-2014,Software Development,Masters,Male,Divorced,2935,1,13,3
20,Nicole,53,31-12-9999,Sales,Masters,Female,Married,15427,2,16,3
21,Angelina,38,31-12-9999,R&D,Doctorate,Female,Single,3944,5,11,3
22,Katherine,24,31-12-9999,Development,Masters,Female,Divorced,4011,0,18,3
23,Sean,36,31-12-9999,Sales,Masters,Male,Single,3407,7,23,4
24,Stella,34,31-12-9999,R&D,Doctorate,Female,Single,11994,0,11,3

In [15]:
Employee_Dataset.dtypes

Employee Name          object
Age                     int64
Last Working Day       object
Department             object
Education              object
Gender                 object
Marital Status         object
Monthly Income          int64
Years of Experience     int64
Percent Salary Hike     int64
Performance Rating      int64
dtype: object

In [16]:
Employee_Dataset["Marital Status"]= Employee_Dataset["Marital Status"].str.replace("Divorced","Single")

In [17]:
# series

In [18]:
Employee_Dataset["Performance Rating"] = Employee_Dataset["Performance Rating"].replace({
    3: 3.45,
    4: 4.45
})  #chain of methods

In [19]:
Employee_Dataset["Performance Rating"]

0     3.45
1     4.45
2     3.45
3     3.45
4     3.45
5     3.45
6     4.45
7     4.45
8     4.45
9     3.45
10    3.45
11    3.45
12    3.45
13    3.45
14    3.45
15    3.45
16    3.45
17    3.45
18    3.45
19    3.45
20    3.45
21    3.45
22    3.45
23    4.45
24    3.45
Name: Performance Rating, dtype: float64

In [20]:
Employee_Dataset["Employee Name"] = Employee_Dataset["Employee Name"].replace({
    "Adam": "hasan"
    
})

In [21]:
Employee_Dataset["Employee Name"]

0        Jitesh
1        Sanjit
2          John
3        Sandra
4         Madhu
5        Robert
6         Megan
7          Matt
8          Will
9        George
10        hasan
11        hasan
12        hasan
13         Emma
14          Vin
15      Richard
16        Clint
17         Kate
18       Morgan
19          Mel
20       Nicole
21     Angelina
22    Katherine
23         Sean
24       Stella
Name: Employee Name, dtype: object

In [22]:
Employee_Dataset.dtypes

Employee Name           object
Age                      int64
Last Working Day        object
Department              object
Education               object
Gender                  object
Marital Status          object
Monthly Income           int64
Years of Experience      int64
Percent Salary Hike      int64
Performance Rating     float64
dtype: object

In [23]:
Employee_Dataset

,Employee Name,Age,Last Working Day,Department,Education,Gender,Marital Status,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
0,Jitesh,41,31-12-9999,Training,Masters,Male,Single,5993,8,11,3.45
1,Sanjit,49,31-12-9999,Sales,Masters,Male,Married,5130,1,23,4.45
2,John,37,31-12-9999,R&D,Doctorate,Male,Single,2090,6,15,3.45
3,Sandra,33,31-12-9999,Software Development,Undergraduate,Female,Married,2909,1,11,3.45
4,Madhu,27,31-12-9999,R&D,Masters,Male,Married,3468,9,12,3.45
5,Robert,32,31-12-9999,R&D,Masters,Male,Single,3068,0,13,3.45
6,Megan,59,31-12-9999,Software Development,Masters,Female,Married,2670,4,20,4.45
7,Matt,30,31-12-9999,R&D,Doctorate,Male,Single,2693,1,22,4.45
8,Will,38,01-03-2012,R&D,Doctorate,Male,Single,9526,0,21,4.45
9,George,36,31-12-9999,Software Development,Masters,NaN,Married,5237,6,13,3.45
10,hasan,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3.45
11,hasan,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3.45
12,hasan,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3.45
13,Emma,29,31-12-9999,Software Development,Undergraduate,Female,Single,4193,0,12,3.45
14,Vin,31,31-12-9999,Software Development,Undergraduate,Male,NaN,2911,1,17,3.45
15,Richard,34,31-12-9999,Software Development,Undergraduate,Male,Single,2661,0,11,3.45
16,Clint,28,31-12-9999,Software Development,Undergraduate,Male,Single,2028,5,14,3.45
17,Kate,29,31-12-9999,Software Development,Undergraduate,Female,NaN,9980,1,11,3.45
18,Morgan,32,31-12-9999,Software Development,Undergraduate,Male,Single,3298,0,12,3.45
19,Mel,22,01-06-2014,Software Development,Masters,Male,Single,2935,1,13,3.45
20,Nicole,53,31-12-9999,Sales,Masters,Female,Married,15427,2,16,3.45
21,Angelina,38,31-12-9999,R&D,Doctorate,Female,Single,3944,5,11,3.45
22,Katherine,24,31-12-9999,Development,Masters,Female,Single,4011,0,18,3.45
23,Sean,36,31-12-9999,Sales,Masters,Male,Single,3407,7,23,4.45
24,Stella,34,31-12-9999,R&D,Doctorate,Female,Single,11994,0,11,3.45

In [24]:
Employee_Dataset.describe()

,Age,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
count,25.00000,25.000000,25.000000,25.000000,25.000000
mean,35.08000,4674.040000,2.320000,14.760000,3.650000
std,8.40595,3427.734474,2.939955,4.075128,0.408248
min,22.00000,2028.000000,0.000000,11.000000,3.450000
25%,30.00000,2670.000000,0.000000,12.000000,3.450000
50%,34.00000,3298.000000,1.000000,13.000000,3.450000
75%,37.00000,5130.000000,5.000000,17.000000,3.450000
max,59.00000,15427.000000,9.000000,23.000000,4.450000

## Task
1. Find Out The Top 5 Selling Items Individual Revenue It Made
2. Total Revenue Of The Top 5 Items Sold
3. Find atleast 2 More questions On The Same Dataset

## Chapter 3 - Pandas Data Structure

- 1D - Series
- 2D - DataFrame

In [25]:
pd.Series(data=[1,2,5.6,"$5.6"])

0       1
1       2
2     5.6
3    $5.6
dtype: object

In [26]:
pd.DataFrame(data={"Names":["Hasan","Abu","Monish","Abdul","Asik"],
                    "Math":[87,89,90,67,3],
                    "Science":[90,98,100,90,99],
                    "Social":[100,70,80,99,100]})

    Names  Math  Science  Social
0   Hasan    87       90     100
1     Abu    89       98      70
2  Monish    90      100      80
3   Abdul    67       90      99
4    Asik     3       99     100

## Task

1. Create a meaningful Series
2. Create a meaningful Dataset using DataFrame with Dict 5 Observation across 6 Features

## Chapter 4 - Filtering & Selection & Sorting

In [27]:
Euro_2012_stats = pd.read_csv("Euro_2012_stats_TEAM.csv")
Euro_2012_stats

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [28]:
Euro_2012_stats.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [29]:
Filtered_euro_data = Euro_2012_stats[["Team", "Goals","Red Cards","Yellow Cards"]]
Filtered_euro_data

                   Team  Goals  Red Cards  Yellow Cards
0               Croatia      4          0             9
1        Czech Republic      4          0             7
2               Denmark      4          0             4
3               England      5          0             5
4                France      3          0             6
5               Germany     10          0             4
6                Greece      5          1             9
7                 Italy      6          0            16
8           Netherlands      2          0             5
9                Poland      2          1             7
10             Portugal      6          0            12
11  Republic of Ireland      1          1             6
12               Russia      5          0             6
13                Spain     12          0            11
14               Sweden      5          0             7
15              Ukraine      2          0             5

In [30]:
Euro_2012_stats

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

#### 4.1 Top 5 Yellow Cards Team

In [31]:
Filtered_euro_data.sort_values("Yellow Cards",ascending = False).head()

        Team  Goals  Red Cards  Yellow Cards
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11
0    Croatia      4          0             9
6     Greece      5          1             9

In [32]:
Filtered_euro_data

                   Team  Goals  Red Cards  Yellow Cards
0               Croatia      4          0             9
1        Czech Republic      4          0             7
2               Denmark      4          0             4
3               England      5          0             5
4                France      3          0             6
5               Germany     10          0             4
6                Greece      5          1             9
7                 Italy      6          0            16
8           Netherlands      2          0             5
9                Poland      2          1             7
10             Portugal      6          0            12
11  Republic of Ireland      1          1             6
12               Russia      5          0             6
13                Spain     12          0            11
14               Sweden      5          0             7
15              Ukraine      2          0             5

#### 4.2 List The Teams Which Has Got Red Cards

In [33]:
Filtered_euro_data[Filtered_euro_data["Red Cards"] == 1]

                   Team  Goals  Red Cards  Yellow Cards
6                Greece      5          1             9
9                Poland      2          1             7
11  Republic of Ireland      1          1             6

#### 4.3 List teams Which has Got more than 8 Yellow Cards

In [34]:
Filtered_euro_data[Filtered_euro_data["Yellow Cards"] >=8]

        Team  Goals  Red Cards  Yellow Cards
0    Croatia      4          0             9
6     Greece      5          1             9
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11

## Task
1. Find out 5 new questions along with the Script Answers

In [35]:
Filtered_euro_data[Filtered_euro_data["Goals"] >=7]

       Team  Goals  Red Cards  Yellow Cards
5   Germany     10          0             4
13    Spain     12          0            11

In [36]:
Filtered_euro_data[Filtered_euro_data["Goals"] == 4]

             Team  Goals  Red Cards  Yellow Cards
0         Croatia      4          0             9
1  Czech Republic      4          0             7
2         Denmark      4          0             4

## Chapter 5 - How to deal with Missing Values

In [37]:
proitbridge_emp_data = pd.read_csv("employee_data.csv")
proitbridge_emp_data

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
0,1001,Rahul Sharma,28.0,Male,IT,Data Analyst,55000,2021-05-12,NaN,4,3,Chennai,rahul@gmail.com
1,1002,Priya Nair,31.0,Female,HR,HR Executive,48000,2020/08/15,NaN,3,5,Bangalore,priya@gmail.com
2,1003,Arjun Kumar,29.0,Male,Finance,Accountant,52000,15-07-2019,NaN,4,4,Hyderabad,arjun@gmail
3,1004,Sneha Reddy,NaN,Female,IT,Software Engineer,65000,2022-01-10,NaN,5,2,Chennai,sneha@gmail.com
4,1005,Vikram Singh,35.0,Male,Sales,Sales Manager,72000,2018-11-25,2024-02-01,4,10,Mumbai,vikram@gmail.com
5,1006,Aisha Khan,27.0,Female,NaN,Data Analyst,54000,2021-06-18,NaN,3,3,Pune,aisha@gmail.com
6,1007,Rohit Das,30.0,Male,IT,Data Scientist,85000,2020-09-14,NaN,5,6,Kolkata,rohit@gmail.com
7,1008,Meena Iyer,26.0,Female,Marketing,Marketing Executive,47000,2023-03-20,NaN,2,1,Chennai,meena@gmail.com
8,1009,Karan Patel,32.0,Male,Finance,Financial Analyst,62000 INR,2019-12-11,NaN,4,7,Ahmedabad,karan@gmail.com
9,1010,Divya Rao,29.0,Female,IT,Software Engineer,68000,2021-07-01,NaN,4,4,Bangalore,divya@gmail.com
10,1011,Rahul Sharma,28.0,Male,IT,Data Analyst,55000,2021-05-12,NaN,4,3,Chennai,rahul@gmail.com
11,1012,Anil Kumar,45.0,Male,Operations,Operations Manager,NaN,2015-04-19,NaN,5,20,Delhi,anil@gmail.com
12,1013,Pooja Verma,24.0,Female,IT,Intern,25000,2024-01-05,NaN,3,0,Chennai,pooja@gmail.com
13,1014,Manoj Raj,38.0,Male,Sales,Sales Executive,51000,2017-09-28,2023-12-15,2,12,Coimbatore,manoj@gmail.com
14,1015,Nisha Gupta,33.0,Female,HR,HR Manager,78000,2016-06-30,NaN,5,9,Delhi,nisha@gmail.com
15,1016,Ajay Kumar,29.0,Male,IT,Data Analyst,not available,2022-10-12,NaN,3,4,Chennai,ajay@gmail.com
16,1017,Kavya Sri,27.0,Female,Finance,Accountant,53000,2021-02-17,NaN,4,3,Hyderabad,kavya@gmail.com
17,1018,Imran Ali,31.0,Male,IT,Software Engineer,69000,2020-05-21,NaN,4,6,Bangalore,imran@gmail.com
18,1019,Deepika Sen,26.0,Female,Marketing,NaN,46000,2023-04-01,NaN,2,1,Kolkata,deepika@gmail.com
19,1020,Suresh Babu,40.0,Male,Operations,Supervisor,58000,2014-08-09,NaN,3,15,Chennai,suresh@gmail.com

## Level 1 of Data Cleaning

### Always Recommended: I'll call to my client , and check with him if he can give the right data

Incase client is asking us to perform the Data cleaning Operation

#### Step 1: Remove Duplicate entries/Records

In [38]:
proitbridge_emp_data.drop_duplicates(inplace = True) #the complete operations will impact the original Dataset

In [39]:
proitbridge_emp_data

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
0,1001,Rahul Sharma,28.0,Male,IT,Data Analyst,55000,2021-05-12,NaN,4,3,Chennai,rahul@gmail.com
1,1002,Priya Nair,31.0,Female,HR,HR Executive,48000,2020/08/15,NaN,3,5,Bangalore,priya@gmail.com
2,1003,Arjun Kumar,29.0,Male,Finance,Accountant,52000,15-07-2019,NaN,4,4,Hyderabad,arjun@gmail
3,1004,Sneha Reddy,NaN,Female,IT,Software Engineer,65000,2022-01-10,NaN,5,2,Chennai,sneha@gmail.com
4,1005,Vikram Singh,35.0,Male,Sales,Sales Manager,72000,2018-11-25,2024-02-01,4,10,Mumbai,vikram@gmail.com
5,1006,Aisha Khan,27.0,Female,NaN,Data Analyst,54000,2021-06-18,NaN,3,3,Pune,aisha@gmail.com
6,1007,Rohit Das,30.0,Male,IT,Data Scientist,85000,2020-09-14,NaN,5,6,Kolkata,rohit@gmail.com
7,1008,Meena Iyer,26.0,Female,Marketing,Marketing Executive,47000,2023-03-20,NaN,2,1,Chennai,meena@gmail.com
8,1009,Karan Patel,32.0,Male,Finance,Financial Analyst,62000 INR,2019-12-11,NaN,4,7,Ahmedabad,karan@gmail.com
9,1010,Divya Rao,29.0,Female,IT,Software Engineer,68000,2021-07-01,NaN,4,4,Bangalore,divya@gmail.com
10,1011,Rahul Sharma,28.0,Male,IT,Data Analyst,55000,2021-05-12,NaN,4,3,Chennai,rahul@gmail.com
11,1012,Anil Kumar,45.0,Male,Operations,Operations Manager,NaN,2015-04-19,NaN,5,20,Delhi,anil@gmail.com
12,1013,Pooja Verma,24.0,Female,IT,Intern,25000,2024-01-05,NaN,3,0,Chennai,pooja@gmail.com
13,1014,Manoj Raj,38.0,Male,Sales,Sales Executive,51000,2017-09-28,2023-12-15,2,12,Coimbatore,manoj@gmail.com
14,1015,Nisha Gupta,33.0,Female,HR,HR Manager,78000,2016-06-30,NaN,5,9,Delhi,nisha@gmail.com
15,1016,Ajay Kumar,29.0,Male,IT,Data Analyst,not available,2022-10-12,NaN,3,4,Chennai,ajay@gmail.com
16,1017,Kavya Sri,27.0,Female,Finance,Accountant,53000,2021-02-17,NaN,4,3,Hyderabad,kavya@gmail.com
17,1018,Imran Ali,31.0,Male,IT,Software Engineer,69000,2020-05-21,NaN,4,6,Bangalore,imran@gmail.com
18,1019,Deepika Sen,26.0,Female,Marketing,NaN,46000,2023-04-01,NaN,2,1,Kolkata,deepika@gmail.com
19,1020,Suresh Babu,40.0,Male,Operations,Supervisor,58000,2014-08-09,NaN,3,15,Chennai,suresh@gmail.com

In [40]:
proitbridge_emp_data.shape

(20, 13)

## Step 2: Find Out The Null Entries

In [41]:
proitbridge_emp_data.isnull().sum()

Employee_ID            0
Name                   0
Age                    1
Gender                 0
Department             1
Job_Title              1
Salary                 1
Joining_Date           0
Last_Working_Day      18
Performance_Rating     0
Experience_Years       0
City                   0
Email                  0
dtype: int64

In [42]:
proitbridge_emp_data.dropna(inplace = True)

In [43]:
proitbridge_emp_data

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
4,1005,Vikram Singh,35.0,Male,Sales,Sales Manager,72000,2018-11-25,2024-02-01,4,10,Mumbai,vikram@gmail.com
13,1014,Manoj Raj,38.0,Male,Sales,Sales Executive,51000,2017-09-28,2023-12-15,2,12,Coimbatore,manoj@gmail.com

In [44]:
proitbridge_emp_data.shape

(2, 13)

### Step 3: Record in a Document 

- Client gave totally 20 observation out of which 18 entries are removed because those records do not have complete information

### step 4: Get Approval  
- send this to client and get the approval to proceed for model building or model training

In [45]:
proitbridge_emp_data.isnull().sum()

Employee_ID           0
Name                  0
Age                   0
Gender                0
Department            0
Job_Title             0
Salary                0
Joining_Date          0
Last_Working_Day      0
Performance_Rating    0
Experience_Years      0
City                  0
Email                 0
dtype: int64

## Level 2 of Data Cleaning

In [46]:
pd.read_excel() #you can import multiple sheets

TypeError: read_excel() missing 1 required positional argument: 'io'

In [ ]:
pd.read_csv() #you can import multiple sheets if it's in one csv file you need to have separate csv file

In [47]:
new_employee_data = pd.read_excel("new_employee_data.xlsx",sheet_name = "new_employee_data")
new_employee_data

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
0,1001,Pooja Verma,25.0,Female,HR,Software Engineer,NaN,2022-01-10,2024-02-01,2,15,Delhi,staff@yahoo.com
1,1002,Sneha Reddy,25.0,Male,Marketing,Marketing Executive,not available,2018-11-25,NaN,5,10,Chennai,wrongemail
2,1003,Meena Iyer,25.0,Female,Finance,Sales Manager,65000,wrong_date,2024-02-01,3,1,Kolkata,staff@yahoo.com
3,1004,Rohit Sharma,22.0,Female,NaN,Marketing Executive,NaN,wrong_date,2023-12-15,2,7,Mumbai,wrongemail
4,1005,Nisha Gupta,35.0,Male,Finance,Marketing Executive,65000,2021-05-12,2023-12-15,5,5,Chennai,wrongemail
5,1006,Divya Nair,22.0,Female,HR,Supervisor,NaN,2018-11-25,NaN,5,5,Delhi,staff@yahoo.com
6,1007,Deepika Sen,NaN,Male,IT,Marketing Executive,85000 INR,15-07-2019,2024-02-01,4,7,Chennai,wrongemail
7,1008,Aisha Khan,40.0,Male,IT,Supervisor,NaN,2018-11-25,NaN,4,3,Chennai,staff@yahoo.com
8,1009,Divya Nair,35.0,Male,Sales,Accountant,NaN,2022-01-10,2023-12-15,2,3,Chennai,wrongemail
9,1010,Rohit Sharma,NaN,Male,IT,Sales Manager,55000,2022-01-10,2024-02-01,4,1,Bangalore,wrongemail
10,1011,Aisha Khan,30.0,Male,NaN,Software Engineer,72000,wrong_date,NaN,2,7,Delhi,staff@yahoo.com
11,1012,Karthik Raj,25.0,Female,NaN,Data Analyst,72000,wrong_date,2024-02-01,2,1,Chennai,wrongemail
12,1013,Pooja Verma,22.0,Male,Sales,Data Analyst,85000 INR,2020/08/15,NaN,2,15,Mumbai,worker@company.com
13,1014,Rahul Das,22.0,Female,NaN,Sales Manager,65000,wrong_date,NaN,2,3,Kolkata,staff@yahoo.com
14,1015,Deepika Sen,35.0,Male,Sales,Software Engineer,85000 INR,2018-11-25,NaN,4,15,Bangalore,worker@company.com
15,1016,Priya Sharma,25.0,Female,Sales,Software Engineer,72000,2022-01-10,NaN,5,2,Kolkata,staff@yahoo.com
16,1017,Rohit Sharma,22.0,Male,Sales,HR Executive,45000,2018-11-25,2023-12-15,2,7,Hyderabad,employee@gmail.com
17,1018,Aisha Khan,NaN,Female,IT,Data Analyst,72000,2021-05-12,2023-12-15,4,3,Delhi,employee@gmail.com
18,1019,Nisha Gupta,22.0,Female,Marketing,Sales Manager,45000,2021-05-12,NaN,4,3,Hyderabad,employee@gmail.com
19,1020,Arun Kumar,40.0,Female,Finance,Supervisor,not available,2022-01-10,2024-02-01,3,15,Delhi,wrongemail
20,1021,Ajay Kumar,28.0,Male,Sales,HR Executive,55000,2018-11-25,2023-12-15,5,5,Kolkata,staff@yahoo.com
21,1022,Divya Nair,35.0,Female,HR,Accountant,85000 INR,15-07-2019,NaN,3,3,Bangalore,worker@company.com
22,1023,Karthik Raj,35.0,Male,NaN,Sales Manager,72000,2020/08/15,2024-02-01,3,10,Bangalore,worker@company.com
23,1024,Priya Sharma,NaN,Male,HR,Accountant,65000,2021-05-12,NaN,3,3,Delhi,employee@gmail.com
24,1025,Mohammed Ali,22.0,Female,Sales,NaN,72000,15-07-2019,2024-02-01,2,5,Kolkata,wrongemail
25,1026,Ajay Kumar,35.0,Male,HR,NaN,65000,2021-05-12,NaN,3,3,Delhi,wrongemail
26,1027,Vikram Singh,30.0,Male,IT,Data Analyst,72000,2021-05-12,2023-12-15,4,3,Delhi,staff@yahoo.com
27,1028,Priya Sharma,40.0,Female,Finance,NaN,65000,2018-11-25,2024-02-01,3,3,Mumbai,employee@gmail.com
28,1029,Meena Iyer,40.0,Female,Sales,Accountant,65000,2022-01-10,2023-12-15,4,2,Pune,worker@company.com
29,1030,Rohit Sharma,22.0,Male,HR,Accountant,85000 INR,2020/08/15,NaN,5,3,Hyderabad,wrongemail
30,1031,Aisha Khan,35.0,Female,Operations,NaN,55000,2021-05-12,2024-02-01,3,15,Delhi,employee@gmail.com
31,1032,Priya Sharma,30.0,Male,Finance,Sales Manager,45000,2018-11-25,NaN,4,7,Mumbai,wrongemail
32,1033,Vikram Singh,30.0,Male,Sales,HR Executive,NaN,2022-01-10,2023-12-15,2,10,Pune,staff@yahoo.com
33,1034,Rohit Sharma,28.0,Male,NaN,Marketing Executive,not available,15-07-2019,NaN,5,1,Chennai,wrongemail
34,1035,Pooja Verma,22.0,Female,HR,HR Executive,65000,2018-11-25,2024-02-01,3,15,Pune,wrongemail
35,1036,Nisha Gupta,NaN,Female,Sales,Sales Manager,65000,2022-01-10,NaN,4,10,Pune,staff@yahoo.com
36,1037,Rohit Sharma,40.0,Male,Operations,Software Engineer,85000 INR,2020/08/15,NaN,2,2,Bangalore,employee@gmail.com
37,1038,Sneha Reddy,25.0,Female,Marketing,HR Executive,55000,2018-11-25,NaN,5,10,Kolkata,staff@yahoo.com
38,1039,Divya Nair,NaN,Male,Operations,Data Analyst,65000,2021-05-12,NaN,2,10,Delhi,staff@yahoo.com
39,1040,Sneha Reddy,28.0,Male,Marketing,Accountant,85000 INR,2020/08/15,2024-02-01,4,10,Bangalore,employee@gmail.com
40,1041,Meena Iyer,35.0,Female,Operations,HR Executive,55000,2018-11-25,NaN,3,15,Bangalore,wrongemail
41,1042,Meena Iyer,25.0,Male,HR,HR Executive,72000,2018-11-25,NaN,3,10,Mumbai,wrongemail
42,1043,Rohit Sharma,40.0,Female,Operations,NaN,55000,2022-01-10,NaN,4,1,Bangalore,worker@company.com
43,1044,Meena Iyer,40.0,Female,Marketing,Marketing Executive,55000,2022-01-10,NaN,3,3,Mumbai,worker@company.com
44,1045,Ajay Kumar,30.0,Male,Operations,Marketing Executive,55000,15-07-2019,2023-12-15,4,1,Pune,employee@gmail.com
45,1046,Divya Nair,40.0,Male,Marketing,Data Analyst,NaN,2018-11-25,NaN,2,3,Kolkata,worker@company.com
46,1047,Karthik Raj,30.0,Male,Sales,Software Engineer,85000 INR,wrong_date,NaN,4,5,Delhi,wrongemail
47,1048,Pooja Verma,22.0,Male,Finance,HR Executive,not available,2020/08/15,NaN,5,2,Mumbai,staff@yahoo.com
48,1049,Ajay Kumar,25.0,Male,NaN,HR Executive,not available,2022-01-10,NaN,5,2,Kolkata,worker@company.com
49,1050,Divya Nair,25.0,Female,Finance,Marketing Executive,55000,15-07-2019,2023-12-15,2,1,Hyderabad,employee@gmail.com

#### Step 1: Drop Duplicates

In [48]:
new_employee_data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [49]:
new_employee_data.drop_duplicates(inplace = True)

In [50]:
new_employee_data

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
0,1001,Pooja Verma,25.0,Female,HR,Software Engineer,NaN,2022-01-10,2024-02-01,2,15,Delhi,staff@yahoo.com
1,1002,Sneha Reddy,25.0,Male,Marketing,Marketing Executive,not available,2018-11-25,NaN,5,10,Chennai,wrongemail
2,1003,Meena Iyer,25.0,Female,Finance,Sales Manager,65000,wrong_date,2024-02-01,3,1,Kolkata,staff@yahoo.com
3,1004,Rohit Sharma,22.0,Female,NaN,Marketing Executive,NaN,wrong_date,2023-12-15,2,7,Mumbai,wrongemail
4,1005,Nisha Gupta,35.0,Male,Finance,Marketing Executive,65000,2021-05-12,2023-12-15,5,5,Chennai,wrongemail
5,1006,Divya Nair,22.0,Female,HR,Supervisor,NaN,2018-11-25,NaN,5,5,Delhi,staff@yahoo.com
6,1007,Deepika Sen,NaN,Male,IT,Marketing Executive,85000 INR,15-07-2019,2024-02-01,4,7,Chennai,wrongemail
7,1008,Aisha Khan,40.0,Male,IT,Supervisor,NaN,2018-11-25,NaN,4,3,Chennai,staff@yahoo.com
8,1009,Divya Nair,35.0,Male,Sales,Accountant,NaN,2022-01-10,2023-12-15,2,3,Chennai,wrongemail
9,1010,Rohit Sharma,NaN,Male,IT,Sales Manager,55000,2022-01-10,2024-02-01,4,1,Bangalore,wrongemail
10,1011,Aisha Khan,30.0,Male,NaN,Software Engineer,72000,wrong_date,NaN,2,7,Delhi,staff@yahoo.com
11,1012,Karthik Raj,25.0,Female,NaN,Data Analyst,72000,wrong_date,2024-02-01,2,1,Chennai,wrongemail
12,1013,Pooja Verma,22.0,Male,Sales,Data Analyst,85000 INR,2020/08/15,NaN,2,15,Mumbai,worker@company.com
13,1014,Rahul Das,22.0,Female,NaN,Sales Manager,65000,wrong_date,NaN,2,3,Kolkata,staff@yahoo.com
14,1015,Deepika Sen,35.0,Male,Sales,Software Engineer,85000 INR,2018-11-25,NaN,4,15,Bangalore,worker@company.com
15,1016,Priya Sharma,25.0,Female,Sales,Software Engineer,72000,2022-01-10,NaN,5,2,Kolkata,staff@yahoo.com
16,1017,Rohit Sharma,22.0,Male,Sales,HR Executive,45000,2018-11-25,2023-12-15,2,7,Hyderabad,employee@gmail.com
17,1018,Aisha Khan,NaN,Female,IT,Data Analyst,72000,2021-05-12,2023-12-15,4,3,Delhi,employee@gmail.com
18,1019,Nisha Gupta,22.0,Female,Marketing,Sales Manager,45000,2021-05-12,NaN,4,3,Hyderabad,employee@gmail.com
19,1020,Arun Kumar,40.0,Female,Finance,Supervisor,not available,2022-01-10,2024-02-01,3,15,Delhi,wrongemail
20,1021,Ajay Kumar,28.0,Male,Sales,HR Executive,55000,2018-11-25,2023-12-15,5,5,Kolkata,staff@yahoo.com
21,1022,Divya Nair,35.0,Female,HR,Accountant,85000 INR,15-07-2019,NaN,3,3,Bangalore,worker@company.com
22,1023,Karthik Raj,35.0,Male,NaN,Sales Manager,72000,2020/08/15,2024-02-01,3,10,Bangalore,worker@company.com
23,1024,Priya Sharma,NaN,Male,HR,Accountant,65000,2021-05-12,NaN,3,3,Delhi,employee@gmail.com
24,1025,Mohammed Ali,22.0,Female,Sales,NaN,72000,15-07-2019,2024-02-01,2,5,Kolkata,wrongemail
25,1026,Ajay Kumar,35.0,Male,HR,NaN,65000,2021-05-12,NaN,3,3,Delhi,wrongemail
26,1027,Vikram Singh,30.0,Male,IT,Data Analyst,72000,2021-05-12,2023-12-15,4,3,Delhi,staff@yahoo.com
27,1028,Priya Sharma,40.0,Female,Finance,NaN,65000,2018-11-25,2024-02-01,3,3,Mumbai,employee@gmail.com
28,1029,Meena Iyer,40.0,Female,Sales,Accountant,65000,2022-01-10,2023-12-15,4,2,Pune,worker@company.com
29,1030,Rohit Sharma,22.0,Male,HR,Accountant,85000 INR,2020/08/15,NaN,5,3,Hyderabad,wrongemail
30,1031,Aisha Khan,35.0,Female,Operations,NaN,55000,2021-05-12,2024-02-01,3,15,Delhi,employee@gmail.com
31,1032,Priya Sharma,30.0,Male,Finance,Sales Manager,45000,2018-11-25,NaN,4,7,Mumbai,wrongemail
32,1033,Vikram Singh,30.0,Male,Sales,HR Executive,NaN,2022-01-10,2023-12-15,2,10,Pune,staff@yahoo.com
33,1034,Rohit Sharma,28.0,Male,NaN,Marketing Executive,not available,15-07-2019,NaN,5,1,Chennai,wrongemail
34,1035,Pooja Verma,22.0,Female,HR,HR Executive,65000,2018-11-25,2024-02-01,3,15,Pune,wrongemail
35,1036,Nisha Gupta,NaN,Female,Sales,Sales Manager,65000,2022-01-10,NaN,4,10,Pune,staff@yahoo.com
36,1037,Rohit Sharma,40.0,Male,Operations,Software Engineer,85000 INR,2020/08/15,NaN,2,2,Bangalore,employee@gmail.com
37,1038,Sneha Reddy,25.0,Female,Marketing,HR Executive,55000,2018-11-25,NaN,5,10,Kolkata,staff@yahoo.com
38,1039,Divya Nair,NaN,Male,Operations,Data Analyst,65000,2021-05-12,NaN,2,10,Delhi,staff@yahoo.com
39,1040,Sneha Reddy,28.0,Male,Marketing,Accountant,85000 INR,2020/08/15,2024-02-01,4,10,Bangalore,employee@gmail.com
40,1041,Meena Iyer,35.0,Female,Operations,HR Executive,55000,2018-11-25,NaN,3,15,Bangalore,wrongemail
41,1042,Meena Iyer,25.0,Male,HR,HR Executive,72000,2018-11-25,NaN,3,10,Mumbai,wrongemail
42,1043,Rohit Sharma,40.0,Female,Operations,NaN,55000,2022-01-10,NaN,4,1,Bangalore,worker@company.com
43,1044,Meena Iyer,40.0,Female,Marketing,Marketing Executive,55000,2022-01-10,NaN,3,3,Mumbai,worker@company.com
44,1045,Ajay Kumar,30.0,Male,Operations,Marketing Executive,55000,15-07-2019,2023-12-15,4,1,Pune,employee@gmail.com
45,1046,Divya Nair,40.0,Male,Marketing,Data Analyst,NaN,2018-11-25,NaN,2,3,Kolkata,worker@company.com
46,1047,Karthik Raj,30.0,Male,Sales,Software Engineer,85000 INR,wrong_date,NaN,4,5,Delhi,wrongemail
47,1048,Pooja Verma,22.0,Male,Finance,HR Executive,not available,2020/08/15,NaN,5,2,Mumbai,staff@yahoo.com
48,1049,Ajay Kumar,25.0,Male,NaN,HR Executive,not available,2022-01-10,NaN,5,2,Kolkata,worker@company.com
49,1050,Divya Nair,25.0,Female,Finance,Marketing Executive,55000,15-07-2019,2023-12-15,2,1,Hyderabad,employee@gmail.com

#### Step 2: identify Null Entries

In [51]:
new_employee_data.isna().sum()

Employee_ID            0
Name                   0
Age                    6
Gender                 0
Department             7
Job_Title              5
Salary                 7
Joining_Date           0
Last_Working_Day      27
Performance_Rating     0
Experience_Years       0
City                   0
Email                  0
dtype: int64

#### Step 3: Go For The Best Imputation

In [52]:
new_employee_data["Department"].unique()

array(['HR', 'Marketing', 'Finance', nan, 'IT', 'Sales', 'Operations'],
      dtype=object)

In [53]:
new_employee_data["Department"]

0             HR
1      Marketing
2        Finance
3            NaN
4        Finance
5             HR
6             IT
7             IT
8          Sales
9             IT
10           NaN
11           NaN
12         Sales
13           NaN
14         Sales
15         Sales
16         Sales
17            IT
18     Marketing
19       Finance
20         Sales
21            HR
22           NaN
23            HR
24         Sales
25            HR
26            IT
27       Finance
28         Sales
29            HR
30    Operations
31       Finance
32         Sales
33           NaN
34            HR
35         Sales
36    Operations
37     Marketing
38    Operations
39     Marketing
40    Operations
41            HR
42    Operations
43     Marketing
44    Operations
45     Marketing
46         Sales
47       Finance
48           NaN
49       Finance
Name: Department, dtype: object

In [54]:
new_employee_data[new_employee_data["Department"] == "Operations"]

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
30,1031,Aisha Khan,35.0,Female,Operations,NaN,55000,2021-05-12,2024-02-01,3,15,Delhi,employee@gmail.com
36,1037,Rohit Sharma,40.0,Male,Operations,Software Engineer,85000 INR,2020/08/15,NaN,2,2,Bangalore,employee@gmail.com
38,1039,Divya Nair,NaN,Male,Operations,Data Analyst,65000,2021-05-12,NaN,2,10,Delhi,staff@yahoo.com
40,1041,Meena Iyer,35.0,Female,Operations,HR Executive,55000,2018-11-25,NaN,3,15,Bangalore,wrongemail
42,1043,Rohit Sharma,40.0,Female,Operations,NaN,55000,2022-01-10,NaN,4,1,Bangalore,worker@company.com
44,1045,Ajay Kumar,30.0,Male,Operations,Marketing Executive,55000,15-07-2019,2023-12-15,4,1,Pune,employee@gmail.com

In [55]:
new_employee_data[new_employee_data["Department"] == "Sales"]

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
8,1009,Divya Nair,35.0,Male,Sales,Accountant,NaN,2022-01-10,2023-12-15,2,3,Chennai,wrongemail
12,1013,Pooja Verma,22.0,Male,Sales,Data Analyst,85000 INR,2020/08/15,NaN,2,15,Mumbai,worker@company.com
14,1015,Deepika Sen,35.0,Male,Sales,Software Engineer,85000 INR,2018-11-25,NaN,4,15,Bangalore,worker@company.com
15,1016,Priya Sharma,25.0,Female,Sales,Software Engineer,72000,2022-01-10,NaN,5,2,Kolkata,staff@yahoo.com
16,1017,Rohit Sharma,22.0,Male,Sales,HR Executive,45000,2018-11-25,2023-12-15,2,7,Hyderabad,employee@gmail.com
20,1021,Ajay Kumar,28.0,Male,Sales,HR Executive,55000,2018-11-25,2023-12-15,5,5,Kolkata,staff@yahoo.com
24,1025,Mohammed Ali,22.0,Female,Sales,NaN,72000,15-07-2019,2024-02-01,2,5,Kolkata,wrongemail
28,1029,Meena Iyer,40.0,Female,Sales,Accountant,65000,2022-01-10,2023-12-15,4,2,Pune,worker@company.com
32,1033,Vikram Singh,30.0,Male,Sales,HR Executive,NaN,2022-01-10,2023-12-15,2,10,Pune,staff@yahoo.com
35,1036,Nisha Gupta,NaN,Female,Sales,Sales Manager,65000,2022-01-10,NaN,4,10,Pune,staff@yahoo.com
46,1047,Karthik Raj,30.0,Male,Sales,Software Engineer,85000 INR,wrong_date,NaN,4,5,Delhi,wrongemail

In [56]:
new_employee_data[new_employee_data["Department"] == "IT"]

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
6,1007,Deepika Sen,NaN,Male,IT,Marketing Executive,85000 INR,15-07-2019,2024-02-01,4,7,Chennai,wrongemail
7,1008,Aisha Khan,40.0,Male,IT,Supervisor,NaN,2018-11-25,NaN,4,3,Chennai,staff@yahoo.com
9,1010,Rohit Sharma,NaN,Male,IT,Sales Manager,55000,2022-01-10,2024-02-01,4,1,Bangalore,wrongemail
17,1018,Aisha Khan,NaN,Female,IT,Data Analyst,72000,2021-05-12,2023-12-15,4,3,Delhi,employee@gmail.com
26,1027,Vikram Singh,30.0,Male,IT,Data Analyst,72000,2021-05-12,2023-12-15,4,3,Delhi,staff@yahoo.com

In [57]:
new_employee_data[new_employee_data["Department"] == "Finance"]

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
2,1003,Meena Iyer,25.0,Female,Finance,Sales Manager,65000,wrong_date,2024-02-01,3,1,Kolkata,staff@yahoo.com
4,1005,Nisha Gupta,35.0,Male,Finance,Marketing Executive,65000,2021-05-12,2023-12-15,5,5,Chennai,wrongemail
19,1020,Arun Kumar,40.0,Female,Finance,Supervisor,not available,2022-01-10,2024-02-01,3,15,Delhi,wrongemail
27,1028,Priya Sharma,40.0,Female,Finance,NaN,65000,2018-11-25,2024-02-01,3,3,Mumbai,employee@gmail.com
31,1032,Priya Sharma,30.0,Male,Finance,Sales Manager,45000,2018-11-25,NaN,4,7,Mumbai,wrongemail
47,1048,Pooja Verma,22.0,Male,Finance,HR Executive,not available,2020/08/15,NaN,5,2,Mumbai,staff@yahoo.com
49,1050,Divya Nair,25.0,Female,Finance,Marketing Executive,55000,15-07-2019,2023-12-15,2,1,Hyderabad,employee@gmail.com

In [58]:
new_employee_data[new_employee_data["Department"] == "Marketing"]

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
1,1002,Sneha Reddy,25.0,Male,Marketing,Marketing Executive,not available,2018-11-25,NaN,5,10,Chennai,wrongemail
18,1019,Nisha Gupta,22.0,Female,Marketing,Sales Manager,45000,2021-05-12,NaN,4,3,Hyderabad,employee@gmail.com
37,1038,Sneha Reddy,25.0,Female,Marketing,HR Executive,55000,2018-11-25,NaN,5,10,Kolkata,staff@yahoo.com
39,1040,Sneha Reddy,28.0,Male,Marketing,Accountant,85000 INR,2020/08/15,2024-02-01,4,10,Bangalore,employee@gmail.com
43,1044,Meena Iyer,40.0,Female,Marketing,Marketing Executive,55000,2022-01-10,NaN,3,3,Mumbai,worker@company.com
45,1046,Divya Nair,40.0,Male,Marketing,Data Analyst,NaN,2018-11-25,NaN,2,3,Kolkata,worker@company.com

In [59]:
new_employee_data[new_employee_data["Department"] == "HR"]

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
0,1001,Pooja Verma,25.0,Female,HR,Software Engineer,NaN,2022-01-10,2024-02-01,2,15,Delhi,staff@yahoo.com
5,1006,Divya Nair,22.0,Female,HR,Supervisor,NaN,2018-11-25,NaN,5,5,Delhi,staff@yahoo.com
21,1022,Divya Nair,35.0,Female,HR,Accountant,85000 INR,15-07-2019,NaN,3,3,Bangalore,worker@company.com
23,1024,Priya Sharma,NaN,Male,HR,Accountant,65000,2021-05-12,NaN,3,3,Delhi,employee@gmail.com
25,1026,Ajay Kumar,35.0,Male,HR,NaN,65000,2021-05-12,NaN,3,3,Delhi,wrongemail
29,1030,Rohit Sharma,22.0,Male,HR,Accountant,85000 INR,2020/08/15,NaN,5,3,Hyderabad,wrongemail
34,1035,Pooja Verma,22.0,Female,HR,HR Executive,65000,2018-11-25,2024-02-01,3,15,Pune,wrongemail
41,1042,Meena Iyer,25.0,Male,HR,HR Executive,72000,2018-11-25,NaN,3,10,Mumbai,wrongemail

### Task

1. Impute The relevent Values in the Salary Column Wharever it is NaN,based on Department Filtering

In [61]:
new_employee_data[new_employee_data["Department"] == "Operations"]

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
30,1031,Aisha Khan,35.0,Female,Operations,NaN,55000,2021-05-12,2024-02-01,3,15,Delhi,employee@gmail.com
36,1037,Rohit Sharma,40.0,Male,Operations,Software Engineer,85000 INR,2020/08/15,NaN,2,2,Bangalore,employee@gmail.com
38,1039,Divya Nair,NaN,Male,Operations,Data Analyst,65000,2021-05-12,NaN,2,10,Delhi,staff@yahoo.com
40,1041,Meena Iyer,35.0,Female,Operations,HR Executive,55000,2018-11-25,NaN,3,15,Bangalore,wrongemail
42,1043,Rohit Sharma,40.0,Female,Operations,NaN,55000,2022-01-10,NaN,4,1,Bangalore,worker@company.com
44,1045,Ajay Kumar,30.0,Male,Operations,Marketing Executive,55000,15-07-2019,2023-12-15,4,1,Pune,employee@gmail.com

In [64]:
new_employee_data[(new_employee_data["Department"] == "Operations") & (new_employee_data["Job_Title"].isna())]

,Employee_ID,Name,Age,Gender,Department,Job_Title,Salary,Joining_Date,Last_Working_Day,Performance_Rating,Experience_Years,City,Email
30,1031,Aisha Khan,35.0,Female,Operations,NaN,55000,2021-05-12,2024-02-01,3,15,Delhi,employee@gmail.com
42,1043,Rohit Sharma,40.0,Female,Operations,NaN,55000,2022-01-10,NaN,4,1,Bangalore,worker@company.com